package com.bingo.auth.core.dao.oauth;

import com.bingo.auth.core.entity.oauth.OauthUser;

public interface OauthUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_user
     *
     * @mbggenerated
     */
    int insert(OauthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_user
     *
     * @mbggenerated
     */
    int insertSelective(OauthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_user
     *
     * @mbggenerated
     */
    OauthUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OauthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OauthUser record);


    OauthUser selectByUserName(String username) ;
}