package com.bingo.auth.core.entity.client;

public class OauthClient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.client_id
     *
     * @mbggenerated
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.client_secret
     *
     * @mbggenerated
     */
    private String clientSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.scope
     *
     * @mbggenerated
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.resource_ids
     *
     * @mbggenerated
     */
    private String resourceIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.authorized_grant_types
     *
     * @mbggenerated
     */
    private String authorizedGrantTypes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.registered_redirect_uris
     *
     * @mbggenerated
     */
    private String registeredRedirectUris;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.auto_approve_scopes
     *
     * @mbggenerated
     */
    private String autoApproveScopes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.authorities
     *
     * @mbggenerated
     */
    private String authorities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.access_token_validity_seconds
     *
     * @mbggenerated
     */
    private Integer accessTokenValiditySeconds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.refresh_token_validity_seconds
     *
     * @mbggenerated
     */
    private Integer refreshTokenValiditySeconds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.additional_information
     *
     * @mbggenerated
     */
    private String additionalInformation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.id
     *
     * @return the value of oauth_client.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.id
     *
     * @param id the value for oauth_client.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.client_id
     *
     * @return the value of oauth_client.client_id
     *
     * @mbggenerated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.client_id
     *
     * @param clientId the value for oauth_client.client_id
     *
     * @mbggenerated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.client_secret
     *
     * @return the value of oauth_client.client_secret
     *
     * @mbggenerated
     */
    public String getClientSecret() {
        return clientSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.client_secret
     *
     * @param clientSecret the value for oauth_client.client_secret
     *
     * @mbggenerated
     */
    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret == null ? null : clientSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.scope
     *
     * @return the value of oauth_client.scope
     *
     * @mbggenerated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.scope
     *
     * @param scope the value for oauth_client.scope
     *
     * @mbggenerated
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.resource_ids
     *
     * @return the value of oauth_client.resource_ids
     *
     * @mbggenerated
     */
    public String getResourceIds() {
        return resourceIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.resource_ids
     *
     * @param resourceIds the value for oauth_client.resource_ids
     *
     * @mbggenerated
     */
    public void setResourceIds(String resourceIds) {
        this.resourceIds = resourceIds == null ? null : resourceIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.authorized_grant_types
     *
     * @return the value of oauth_client.authorized_grant_types
     *
     * @mbggenerated
     */
    public String getAuthorizedGrantTypes() {
        return authorizedGrantTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.authorized_grant_types
     *
     * @param authorizedGrantTypes the value for oauth_client.authorized_grant_types
     *
     * @mbggenerated
     */
    public void setAuthorizedGrantTypes(String authorizedGrantTypes) {
        this.authorizedGrantTypes = authorizedGrantTypes == null ? null : authorizedGrantTypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.registered_redirect_uris
     *
     * @return the value of oauth_client.registered_redirect_uris
     *
     * @mbggenerated
     */
    public String getRegisteredRedirectUris() {
        return registeredRedirectUris;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.registered_redirect_uris
     *
     * @param registeredRedirectUris the value for oauth_client.registered_redirect_uris
     *
     * @mbggenerated
     */
    public void setRegisteredRedirectUris(String registeredRedirectUris) {
        this.registeredRedirectUris = registeredRedirectUris == null ? null : registeredRedirectUris.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.auto_approve_scopes
     *
     * @return the value of oauth_client.auto_approve_scopes
     *
     * @mbggenerated
     */
    public String getAutoApproveScopes() {
        return autoApproveScopes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.auto_approve_scopes
     *
     * @param autoApproveScopes the value for oauth_client.auto_approve_scopes
     *
     * @mbggenerated
     */
    public void setAutoApproveScopes(String autoApproveScopes) {
        this.autoApproveScopes = autoApproveScopes == null ? null : autoApproveScopes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.authorities
     *
     * @return the value of oauth_client.authorities
     *
     * @mbggenerated
     */
    public String getAuthorities() {
        return authorities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.authorities
     *
     * @param authorities the value for oauth_client.authorities
     *
     * @mbggenerated
     */
    public void setAuthorities(String authorities) {
        this.authorities = authorities == null ? null : authorities.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.access_token_validity_seconds
     *
     * @return the value of oauth_client.access_token_validity_seconds
     *
     * @mbggenerated
     */
    public Integer getAccessTokenValiditySeconds() {
        return accessTokenValiditySeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.access_token_validity_seconds
     *
     * @param accessTokenValiditySeconds the value for oauth_client.access_token_validity_seconds
     *
     * @mbggenerated
     */
    public void setAccessTokenValiditySeconds(Integer accessTokenValiditySeconds) {
        this.accessTokenValiditySeconds = accessTokenValiditySeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.refresh_token_validity_seconds
     *
     * @return the value of oauth_client.refresh_token_validity_seconds
     *
     * @mbggenerated
     */
    public Integer getRefreshTokenValiditySeconds() {
        return refreshTokenValiditySeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.refresh_token_validity_seconds
     *
     * @param refreshTokenValiditySeconds the value for oauth_client.refresh_token_validity_seconds
     *
     * @mbggenerated
     */
    public void setRefreshTokenValiditySeconds(Integer refreshTokenValiditySeconds) {
        this.refreshTokenValiditySeconds = refreshTokenValiditySeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.additional_information
     *
     * @return the value of oauth_client.additional_information
     *
     * @mbggenerated
     */
    public String getAdditionalInformation() {
        return additionalInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.additional_information
     *
     * @param additionalInformation the value for oauth_client.additional_information
     *
     * @mbggenerated
     */
    public void setAdditionalInformation(String additionalInformation) {
        this.additionalInformation = additionalInformation == null ? null : additionalInformation.trim();
    }
}