package com.bingo.auth.core.entity.resource;

public class OauthResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.resource_url
     *
     * @mbggenerated
     */
    private String resourceUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.id
     *
     * @return the value of oauth_resource.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.id
     *
     * @param id the value for oauth_resource.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.role_name
     *
     * @return the value of oauth_resource.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.role_name
     *
     * @param roleName the value for oauth_resource.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.resource_url
     *
     * @return the value of oauth_resource.resource_url
     *
     * @mbggenerated
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.resource_url
     *
     * @param resourceUrl the value for oauth_resource.resource_url
     *
     * @mbggenerated
     */
    public void setResourceUrl(String resourceUrl) {
        this.resourceUrl = resourceUrl == null ? null : resourceUrl.trim();
    }
}