package com.bingo.auth.core.dao.client;

import com.bingo.auth.core.entity.client.OauthClient;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface OauthClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client
     *
     * @mbggenerated
     */
    int insert(OauthClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client
     *
     * @mbggenerated
     */
    int insertSelective(OauthClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client
     *
     * @mbggenerated
     */
    OauthClient selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OauthClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OauthClient record);


    OauthClient selectByClientId(String clientId);
}